// export const _getCount = (state) => state.example.count;
export const _userInfoError = (state) => state.authUser.userInfoError;
export const _userInfoSuccess = (state) => state.authUser.userInfoSuccess;
export const _isAuth = (state) => state.authUser.isAuth;
export const _goalCategoriesInfo = (state) => state.goal.goalCategoriesInfo;
export const _goalCategoriesError = (state) => state.goal.goalCategoriesError;
export const _goalInfo = (state) => state.goal.goalInfo;
export const _goalError = (state) => state.goal.goalError;
export const _goalIdInfo = (state) => state.goal.goalIdInfo;
export const _goalIdError = (state) => state.goal.goalIdError;
